#!/bin/bash

if [ -z "$1" ] || [ -z "$2" ]
then
	echo "Usage: $0 <input_file.c> <output_file>"
else
	cd ..
	gcc -g -m32 -Wl,--allow-multiple-definition -ffreestanding -nostartfiles -nostdlib -fno-stack-protector $(./get_deps $1) kernel/drivers/utils/*.c kernel/cpu/*.c build/kernel/interrupt.o external_programs/$1 -o external_programs/$2 -T ld/program.ld
fi

