#!/bin/sh

mkdir virtual_disks
rm virtual_disks/*.bin virtual_disks/*.vmdk

vmkd_uuids=$(cat disk_uuids.txt)
drive_i=1

for uuid in $vmkd_uuids
do
	dd if=/dev/zero of="virtual_disks/drive_$drive_i.bin" bs=1024 count=102400
	VBoxManage convertfromraw "virtual_disks/drive_$drive_i.bin" "virtual_disks/drive_$drive_i.vmdk" --format VMDK
	VBoxManage internalcommands sethduuid "virtual_disks/drive_$drive_i.vmdk" $uuid
	drive_i=$((drive_i+1))
done

