#!/bin/sh

qemu-system-i386 -display gtk,gl=on -drive format=raw,file=os-image.bin -drive format=raw,file=virtual_disks/drive_1.bin -drive format=raw,file=virtual_disks/drive_2.bin -drive format=raw,file=virtual_disks/drive_3.bin
